def welcome_message():
    print("#                                #")
    print("#________________________________#")
    print("# *            *          *      #")
    print("#       *                        #")
    print("#    Welcome to use MOVIETRON    #")
    print("#           *       *            #")
    print("#     *       *              *   #")
    print("# ______________________________ #")
    print("#                                #")
